source "http://rubygems.org"

group :test do
  gem "rake"
  gem "puppet", ENV['PUPPET_VERSION'] || '~> 3.4.0'
  gem "puppet-lint"
  gem "rspec-puppet", :git => 'https://github.com/rodjek/rspec-puppet.git'
  gem "puppet-syntax"
  gem "puppetlabs_spec_helper"
end

group :development do
  gem "travis"
  gem "travis-lint"
  gem "beaker", ">= 1.8.0"
  gem "beaker-rspec", ">= 2.2.0"
  gem "vagrant-wrapper"
  gem "puppet-blacksmith"
  gem "guard-rake", ">= 0.0.10"
end
