source "http://rubygems.org"

group :test do
  gem "rake", ">= 12.3.3"
  gem "puppet", ">= 6.25.1", ENV['PUPPET_VERSION'] || '~> 3.4.0'
  gem "puppet-lint"
  gem "rspec-puppet", :git => 'https://github.com/rodjek/rspec-puppet.git'
  gem "puppet-syntax"
  gem "puppetlabs_spec_helper"
end

group :development do
  gem "travis"
  gem "travis-lint"
  gem "beaker", ">= 3.7.0"
  gem "beaker-rspec", ">= 6.0.0"
  gem "vagrant-wrapper"
  gem "puppet-blacksmith"
  gem "guard-rake"
end
