source "http://rubygems.org"


gem "rake", ">= 12.3.3"
gem "puppet", ">= 6.25.1", ENV['PUPPET_VERSION'] || '~> 3.2.0'
gem "puppet-lint"
gem "rspec-puppet", '~> 1.0.0'
gem "puppetlabs_spec_helper"
gem "rspec-system-puppet"
gem "vagrant-wrapper"
gem "puppet-syntax"

group :development do
  gem "puppet-blacksmith"
end
