source "http://rubygems.org"


gem "rake"
gem "puppet", ">= 6.25.1", ENV['PUPPET_VERSION'] || '~> 3.2.0'
gem "puppet-lint"
gem "rspec-puppet", '~> 1.0.0'
gem "puppetlabs_spec_helper"
gem "rspec-system-puppet"
gem "vagrant-wrapper"
gem "puppet-syntax", ">= 1.1.0"

group :development do
  gem "puppet-blacksmith", ">= 2.0.2"
end
